Add mzData extractor.
Add isa2mzdata tool.
Remove big files in test, and write new small/empty test resource files.

diff --git a/test/test-extract-from-isa b/test/test-extract-from-isa
--- a/test/test-extract-from-isa
+++ b/test/test-extract-from-isa
@@ -7,14 +7,46 @@ PROG_NAME=$(basename $0)
 PROG_PATH=$(dirname $0)
 RES_PATH=$PROG_PATH/res
 
+# Error {{{1
+################################################################
+
+function error {
+
+	local msg=$1
+
+	echo "ERROR: $msg" >&2
+
+	exit 1
+}
+
+# Test study {{{1
+################################################################
+
+function test_study {
+	study_name=$1
+	ext=$2
+	n_expected_files=$3
+	input_path="$PROG_PATH/res/${study_name}"
+	output_path="$PROG_PATH/${study_name}_extract"
+
+	# Remove existing output
+	rm -rf "$output_path"
+
+	# Call program
+	"$PROG_PATH/../extract-from-isa" -i "$input_path" -o "$output_path" -e $ext
+
+	# Check output
+	n_files=$(ls "$output_path/" | wc -l)
+	n_right_ext_files=$(find "$output_path" -iname "*.$ext" | wc -l)
+	[[ $n_files -eq $n_expected_files ]] || error "Error while extracting $ext files from $study_name. Extracted $n_files instead of $n_expected_files."
+	[[ $n_files -eq $n_right_ext_files ]] || error "Error while extracting $ext files from $study_name. $n_right_ext_files extracted files have the right extension. Was expecting $n_expected_files."
+}
+
 # MAIN {{{1
 ################################################################
 
-# Test MTBLS291
-output_path="$PROG_PATH/mtbls291-mzmls"
-rm -rf "$output_path"
-"$PROG_PATH/../extract-from-isa" -g -i "$PROG_PATH/res/MTBLS291_subset" -o "$output_path" -e mzML
-n_files=$(ls -1 "$output_path"/* | wc -l)
-n_mzml_files=$(ls -1 "$output_path"/*.mzML | wc -l)
-[[ $n_files -eq $n_mzml_files ]] || exit 1
-[[ $n_files -eq 2 ]] || exit 2
+# Test on different studies
+test_study empty_study mzML 0
+test_study fake_mzml_study mzML 1
+test_study fake_mzdata_study mzData 1
+test_study fake_case_insensitive_mzml_study mzML 3
