Add option for creating symlinks instead of copying.

diff --git a/test/test-extract-from-isa b/test/test-extract-from-isa
--- a/test/test-extract-from-isa
+++ b/test/test-extract-from-isa
@@ -23,23 +23,47 @@ function error {
 ################################################################
 
 function test_study {
-	study_name=$1
-	ext=$2
-	n_expected_files=$3
-	input_path="$PROG_PATH/res/${study_name}"
-	output_path="$PROG_PATH/${study_name}_extract"
+	local study_name=$1
+	local ext=$2
+	local n_expected_files=$3
+	local input_path="$PROG_PATH/res/${study_name}"
+	local output_path="$PROG_PATH/${study_name}_extract"
 
 	# Remove existing output
 	rm -rf "$output_path"
 
 	# Call program
-	"$PROG_PATH/../extract-from-isa" -i "$input_path" -o "$output_path" -e $ext
+	"$PROG_PATH/../extract-from-isa" -i "$input_path" -o "$output_path" -e $ext || exit 1
 
 	# Check output
-	n_files=$(ls "$output_path/" | wc -l)
-	n_right_ext_files=$(find "$output_path" -iname "*.$ext" | wc -l)
+	local n_files=$(ls "$output_path/" | wc -l)
+	local n_right_ext_files=$(find "$output_path" -iname "*.$ext" | wc -l)
 	[[ $n_files -eq $n_expected_files ]] || error "Error while extracting $ext files from $study_name. Extracted $n_files instead of $n_expected_files."
 	[[ $n_files -eq $n_right_ext_files ]] || error "Error while extracting $ext files from $study_name. $n_right_ext_files extracted files have the right extension. Was expecting $n_expected_files."
+}
+
+# Test symbolic links {{{1
+################################################################
+
+test_symlinks() {
+
+	local study_name=fake_mzml_study
+	local ext=mzML
+	local n_expected_files=1
+	local input_path="$PROG_PATH/res/${study_name}"
+	local output_path="$PROG_PATH/${study_name}_extract_symlinks"
+
+	# Remove existing output
+	rm -rf "$output_path"
+
+	# Call program
+	"$PROG_PATH/../extract-from-isa" -i "$input_path" -o "$output_path" -e $ext -s || exit 1
+
+	# Check output
+	local n_files=$(ls "$output_path/" | wc -l)
+	[[ $n_files -eq $n_expected_files ]] || error "Error while extracting $ext files from $study_name. Extracted $n_files instead of $n_expected_files."
+	extracted_file=$(ls "$output_path/")
+	[[ -L $output_path/$extracted_file ]] || error "Extracted file $output_path/$extracted_file is not a symbolic link."
 }
 
 # MAIN {{{1
@@ -53,3 +77,4 @@ test_study fake_mzxml_study mzXML 1
 test_study fake_nmrml_study nmrML 1
 test_study fake_netcdf_study CDF 1
 test_study fake_case_insensitive_mzml_study mzML 3
+test_symlinks
